### ISSUE TITLE
Todo

### ISSUE THREAD

**Issue by izaiasmachado** [izaiasmachado/rock-paper-scissors#1]
- [x] **Backend**
  - [x] Socket.io communication
  - [x] Limit number of players
  - [x] Gamerules

---

- [x] **Frontend**
  - [x] Trying to connect page
  - [x] Design
  - [x] Add link to Github Repository

---

- [x] **Create Github documentation**
  - [x] Add GIF

---
- Future ideas
  - [ ] Scoreboard
  - [ ] Multiple game rooms
